"""adding wallet group

Revision ID: 0cb6646be441
Revises: 15961785bd5d
Create Date: 2025-07-28 03:56:13.769091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb6646be441'
down_revision: Union[str, Sequence[str], None] = '15961785bd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('user_phone_numbers', sa.JSON(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_groups_id'), 'wallet_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_groups_id'), table_name='wallet_groups')
    op.drop_table('wallet_groups')
    # ### end Alembic commands ###
