"""adding wallet group

Revision ID: 23f5ca82be6f
Revises: 0cb6646be441
Create Date: 2025-07-28 04:32:30.648910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f5ca82be6f'
down_revision: Union[str, Sequence[str], None] = '0cb6646be441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_groups', sa.Column('building_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'wallet_groups', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_groups', type_='foreignkey')
    op.drop_column('wallet_groups', 'building_id')
    # ### end Alembic commands ###
