"""test

Revision ID: 465a1ebb7ab8
Revises: dd62ba3d4ed6
Create Date: 2025-07-09 11:35:30.627423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465a1ebb7ab8'
down_revision: Union[str, Sequence[str], None] = 'dd62ba3d4ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_states_state_id'), 'states', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_states_state_id'), 'states', ['state_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
