"""adding stalls

Revision ID: 83699900514a
Revises: e0e52236ff1f
Create Date: 2025-06-30 13:53:23.180101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83699900514a'
down_revision: Union[str, Sequence[str], None] = 'e0e52236ff1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stalls', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stalls', 'image_url')
    # ### end Alembic commands ###
