"""added token column

Revision ID: 893e515b38f1
Revises: dcb706f4e4a3
Create Date: 2025-08-02 13:11:47.743304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893e515b38f1'
down_revision: Union[str, Sequence[str], None] = 'dcb706f4e4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('token_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'token_number')
    # ### end Alembic commands ###
