"""adding country

Revision ID: 8cb04094366a
Revises: 7478ff67e4ea
Create Date: 2025-06-28 12:36:53.501868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb04094366a'
down_revision: Union[str, Sequence[str], None] = '7478ff67e4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('selected_country', sa.Enum('india', 'kenya', 'usa', 'philippines', 'canada', 'malaysia', 'ksa', 'bahrain', 'nepal', 'ireland', 'nigeria', 'finland', 'china', 'japan', 'denmark', 'france', 'south_korea', name='countryenum'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
