"""adding password

Revision ID: 928a91065bc5
Revises: b461293dd4a6
Create Date: 2025-06-30 12:29:09.990856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928a91065bc5'
down_revision: Union[str, Sequence[str], None] = 'b461293dd4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'password')
    # ### end Alembic commands ###
