"""adding user

Revision ID: aed49a8f34dd
Revises: 436aa98d9396
Create Date: 2025-07-07 14:33:06.669160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed49a8f34dd'
down_revision: Union[str, Sequence[str], None] = '436aa98d9396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('otp_verified_via', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'otp_verified_via')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
