"""adding items

Revision ID: ba1b501fa93f
Revises: 768475a7ffdd
Create Date: 2025-06-30 15:51:54.436971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1b501fa93f'
down_revision: Union[str, Sequence[str], None] = '768475a7ffdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('Gst_precentage', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('final_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'final_price')
    op.drop_column('items', 'Gst_precentage')
    # ### end Alembic commands ###
