"""adding user

Revision ID: bcaec706a005
Revises: aed49a8f34dd
Create Date: 2025-07-08 12:03:11.392095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcaec706a005'
down_revision: Union[str, Sequence[str], None] = 'aed49a8f34dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_stalls_id'), table_name='stalls')
    op.drop_table('stalls')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_users_company_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax_included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stall_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('Gst_precentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('items_admin_id_fkey')),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('items_building_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('items_category_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('items_manager_id_fkey')),
    sa.ForeignKeyConstraint(['stall_id'], ['stalls.id'], name=op.f('items_stall_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_otp_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_verified_via', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('users_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_company_email'), 'users', ['company_email'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('selected_country', postgresql.ENUM('india', 'kenya', 'usa', 'philippines', 'canada', 'malaysia', 'ksa', 'bahrain', 'nepal', 'ireland', 'nigeria', 'finland', 'china', 'japan', 'denmark', 'france', 'south_korea', name='countryenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name='country_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='country_pkey'),
    sa.UniqueConstraint('admin_id', name='country_admin_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stall_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('categories_admin_id_fkey')),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('categories_building_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('categories_manager_id_fkey')),
    sa.ForeignKeyConstraint(['stall_id'], ['stalls.id'], name=op.f('categories_stall_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_access', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='buildings_city_id_fkey'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='buildings_country_id_fkey'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='buildings_state_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name='buildings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='buildings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('stalls',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('building_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manager_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('stalls_admin_id_fkey')),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('stalls_building_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('stalls_manager_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stalls_pkey'))
    )
    op.create_index(op.f('ix_stalls_id'), 'stalls', ['id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey'),
    sa.UniqueConstraint('phone_number', name='admin_users_phone_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name='cities_admin_id_fkey'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='cities_country_id_fkey'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='cities_state_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.VARCHAR(), server_default=sa.text("'Unknown'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='states_country_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['admin_users.id'], name='states_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='states_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('managers_admin_id_fkey')),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('managers_building_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('managers_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('managers_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    # ### end Alembic commands ###
