"""updating Wallet

Revision ID: c9f051f2e6b0
Revises: b1ed0e23ed26
Create Date: 2025-07-23 15:34:14.848303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f051f2e6b0'
down_revision: Union[str, Sequence[str], None] = 'b1ed0e23ed26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('building_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'wallets', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'building_id')
    # ### end Alembic commands ###
