"""adding state

Revision ID: cf3522ecb567
Revises: c9878427e979
Create Date: 2025-06-28 14:47:48.488293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3522ecb567'
down_revision: Union[str, Sequence[str], None] = 'c9878427e979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.drop_index(op.f('ix_vendor_locations_id'), table_name='vendor_locations')
    op.drop_table('vendor_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_locations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('vendor_locations_country_id_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['admin_users.id'], name=op.f('vendor_locations_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_locations_pkey'))
    )
    op.create_index(op.f('ix_vendor_locations_id'), 'vendor_locations', ['id'], unique=False)
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###
